name: build and publish a snapshot

on:
  push:
    branches:
      - master
      - 'snapshot/*'
      - 'kotlin-*'
    paths-ignore:
      - '**.md'
      - '**.adoc'
      - '**/.gitignore'
      - './github/**'
      - '!./github/workflow/snapshot.yml'

env:
  SONATYPE_USERNAME: ${{ secrets.sonatype_username }}
  SONATYPE_PASSWORD: ${{ secrets.sonatype_password }}

jobs:
  build-upload:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - name: Check out
        uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Cached Konan
        uses: actions/cache@v2
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-konan-
      - name: Cached Gradle
        uses: actions/cache@v2
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: '8.0.265'
      - name: Setup Android SDK dir
        if: matrix.os != 'windows-latest'
        run: echo sdk.dir=$ANDROID_HOME > local.properties
      - name: install default NDK for AGP
        if: matrix.os != 'windows-latest'
        run: $ANDROID_HOME/tools/bin/sdkmanager "ndk;21.3.6528147"
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Set up Windows
        if: matrix.os == 'windows-latest'
        run: |
          rm.exe "C:/WINDOWS/system32/bash.EXE"
          echo "C:\msys64\usr\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          # https://youtrack.jetbrains.com/issue/KT-42485
          echo "LIBCLANG_DISABLE_CRASH_RECOVERY=1" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      - name: Setup kodein.local.properties
        run: cp .github/conf/kodein.local.${{ matrix.os }}.properties kodein.local.properties
      - name: Set up Gradle & Konan
        shell: bash
        run: ./gradlew
      # Host only for MacOS / Windows
      - name: Check (macos / windows)
        if: matrix.os != 'ubuntu-latest'
        run: ./gradlew hostOnlyTest
        shell: bash
      - name: Check Android (macos)
        if: matrix.os == 'macos-latest'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          arch: x86_64
          ndk: 21.3.6528147
          cmake: 3.10.2.4988404
          script: ./gradlew connectedCheck
      - name: Upload (macos / windows)
        if: matrix.os != 'ubuntu-latest'
        shell: bash
        run: ./gradlew hostOnlyPublish -PgitRef=${{ github.ref }} -Psnapshot=true --stacktrace
        # Publish all on Ubuntu
      - name: Check (ubuntu)
        if: matrix.os == 'ubuntu-latest'
        shell: bash
        run: ./gradlew linuxX64Test
      - name: Upload (ubuntu)
        if: matrix.os == 'ubuntu-latest'
        shell: bash
        run: ./gradlew publishAllPublicationsToOssrhStagingRepository -PgitRef=${{ github.ref }} -Psnapshot=true --stacktrace
